version: '3'

services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    container_name: comercio
    restart: always
    volumes:
      -comercio-disk:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ecomm
      POSTGRES_PASSWORD: 711179
      POSTGRES_DB: comercio

volumes:
  comercio-disk: